version: "3.9"

services:
  ldap:
    build: ./ldap-server
    container_name: ldap
    ports:
      - "8389:389"
    volumes:
      - ./volumes/ldap-data:/var/lib/ldap
    restart: unless-stopped
    networks: [appnet]

  apache:
    build:
      context: ./web-server
    container_name: apache_ssl
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./volumes/apache-html:/var/www/html
    depends_on:
      - ldap
    restart: always
    networks:
      - appnet

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=ldap
    ports:
      - "8081:80"
    depends_on:
      - ldap
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

