services:
  ldap:
    build: ./ldap-server
    container_name: ldap
    env_file:
      - .env
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
      - LDAP_READONLY_USER=${LDAP_READONLY_USER}
      - LDAP_READONLY_USER_USERNAME=${LDAP_READONLY_USER_USERNAME:-readonly}
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD:-readonly-pass}
    ports:
      - "8389:389"
    volumes:
      - ./volumes/ldap-data:/var/lib/ldap
    restart: unless-stopped
    networks: [appnet]

  apache:
    build:
      context: ./web-server
    container_name: apache_ssl
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./volumes/apache-html:/var/www/html
      - ./volumes/apache-settings:/var/www
    depends_on:
      - ldap
    restart: always
    networks:
      - appnet

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "9081:80"
    depends_on:
      - ldap
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

